-- Canonical CSV pairs: 402
WITH csv_canonical(order_code, full_name) AS (
  VALUES
  ('DKX3K','Aymila Ayhan'),
  ('SL5RL','Paula Ullrich'),
  ('7EGCA','Karla Portalanza'),
  ('7EGCA','Fabiola portalanza'),
  ('F9JA4','Irene Orbañanos'),
  ('F9JA4','María Fernández Pérez'),
  ('F9JA4','Estela Colado'),
  ('9UWFU','Dragomir Maria Andreea Stefania'),
  ('9UWFU','Vlaicu Alexandra'),
  ('R6MD7','Eser Murat Yilmaz'),
  ('R6MD7','Emre Keskin'),
  ('R6MD7','Anibal Montenegro'),
  ('7EGT9','Nazik Kssiouar'),
  ('3STCF','Madujibeya Alu'),
  ('3STCF','Rena Seyidova'),
  ('ERVAV','Verena Kress'),
  ('24HTE','Nik Langenakers'),
  ('3STW2','Ian Gaffney'),
  ('F9JXA','Janna Kirkby'),
  ('F9JXA','Alina Vakhner'),
  ('PT9KU','Carmen Fakler'),
  ('ZG239','Alexandra Faragau'),
  ('7EGHH','Rebecca kirkby'),
  ('7EGHH','Melissa hardege'),
  ('NPF2F','Tine De Batselier'),
  ('YXE9C','Sarah'),
  ('UY7FJ','Delfino Romero'),
  ('UY7FJ','Delfino'),
  ('KZC5Z','Nadir Moda'),
  ('KZC5Z','Linda Zanotto'),
  ('PT94T','Adriana Ramos'),
  ('PT94T','Alexandre Lino'),
  ('PT94T','Tania Sofía Medeiros'),
  ('C26YM','Kamau D JORDAN'),
  ('C26YM','Julia M Menninga'),
  ('ERVWD','Rui Li'),
  ('ERVWD','Yuanyuan Dai'),
  ('GV4K6','Alexander Gauss'),
  ('M3PGV','Marina CHAMBON'),
  ('M3PGV','Frédéric Pisinger'),
  ('6H3E9','Laura Fontan'),
  ('6H3E9','Angela Norman'),
  ('C26YY','Mariana Amaral Gouveia'),
  ('UY775','Sam Spring'),
  ('UY775','Fatma Abdel Raouf'),
  ('JWKK2','Ozan Toker'),
  ('JWKK2','Sharon Keya'),
  ('HASSF','Kahil Nayton'),
  ('M3PP9','BACHIRI Mehdi'),
  ('ERVVN','Petter Woxen'),
  ('ERVVS','Ilinca Dascalescu'),
  ('ERVVS','Alexandra Albu'),
  ('VMNN5','Fernanda Martinez'),
  ('24JGN','Biana Rivero Kuzmina'),
  ('24JGN','Elizabeth Brandt'),
  ('4NWVY','Marouane BOUDJEMA'),
  ('9UVTF','Alfonso tercero Fernández'),
  ('NP75J','FABIO FIADONE'),
  ('NP75J','Davide Pagliara'),
  ('9UVH6','Sonja Jutte'),
  ('KZATY','Nataliya Beer'),
  ('KZATY','Roland Beer'),
  ('ZGF5P','Annamira Szirmai'),
  ('ZGF5P','Williams MERIDA PARARD'),
  ('XCSED','Charlotte Burgers'),
  ('XCSED','Romée Prösch'),
  ('ZGFCT','Rita Campainha'),
  ('6HDML','Simon Reuter'),
  ('C2LRN','Elian Stolarsky'),
  ('C2LRN','Esperanza Guirado'),
  ('4NWJG','Simone Nuspl'),
  ('4NWJG','Dorothea Ziegler'),
  ('4NWJG','Carmen Blanka'),
  ('R65T9','Anthony Britto'),
  ('AFZ3H','Vania Spinelli'),
  ('AFZ3H','Greta Baldan'),
  ('4NWRT','Kristijan Jager'),
  ('5D6MV','Eser Murat Yilmaz'),
  ('W7NT5','Norika Majidi'),
  ('7EP5M','María Gómez Virseda'),
  ('7EPCK','Ali Zalpour'),
  ('ERTCD','Tereza Kopecka'),
  ('GVE3U','Andreea Broasca'),
  ('XCK3C','Steve Thomas'),
  ('6H25E','Sekela Nancy Ngamilo'),
  ('T5SER','Norma Brigido'),
  ('T5SER','Guest'),
  ('DKJZ2','Jacqueline Bougouneau'),
  ('DKJZ2','Eddie Hunt'),
  ('NPMTS','Minjung son'),
  ('AFNDE','Ms Giorgia Muziani'),
  ('KZWL9','LEE MINYOUNG'),
  ('6H26G','Ivanka Brajovic'),
  ('NPMUC','Paul-Robert Marcu'),
  ('ERXCL','DJ Tuli Mar'),
  ('ERXCL','Sabrina Lo Iacono'),
  ('DKJVG','Anton Pimenov'),
  ('DKJVG','Anastasiia Stashevskaia'),
  ('4NVC3','Bahram Al Khamisi'),
  ('7EYJW','Mirte Andeweg'),
  ('UY57L','Camille Fournier'),
  ('GVEEL','Karen Marutyan'),
  ('GVEEL','Anna Zolotenko'),
  ('PT33S','Orsolya Bereczki'),
  ('PT33S','Francis Eastman'),
  ('VMSKX','Simon Rowley'),
  ('VMSKX','Raquel Gimeno'),
  ('F9Y6C','Lei Portalanza'),
  ('F9Y6C','Nicolle McDonagh'),
  ('VMSKG','Anna Huszár Enikő'),
  ('VMSKG','Lina Tóth'),
  ('VMSKG','Dániel Nyikos'),
  ('VMSKG','Anna)'),
  ('R6AW3','Serena McGuinness'),
  ('R6AW3','Deepesh Mistry'),
  ('9UXH5','Razvan Mircea Tasnadi'),
  ('9UXH5','Serban Andrei Ionescu'),
  ('24PYT','Bianca Badaruta'),
  ('24PYT','Eduard Friedrich'),
  ('YX2F3','PATRICIA SAINZ ILUNDAIN'),
  ('YX2F3','BEATRIZ RUIZ LARUMBE'),
  ('YX2F3','PEDRO PONS MALDONADO'),
  ('AFURR','Bahman Pasha'),
  ('AFURR','Evelina Klanikova'),
  ('HA93D','Lionel Pereira'),
  ('4NTHG','MINGYUE YE'),
  ('JWEDF','traa'),
  ('M3LNK','Cristina De Mena González'),
  ('VMS4D','Gina Malin'),
  ('DKGYR','Von Veltheim Nadia'),
  ('LJ75H','Livia'),
  ('9UXJR','Adrian Marius Soós'),
  ('9UXJR','Mária Kovacsics'),
  ('VMS4C','Florin Mihaescu'),
  ('NP5AR','Gregory Moureau'),
  ('F9YLM','Oleksiy Sokolov'),
  ('F9YLM','Maryia Ambrushkevich'),
  ('4NTH2','Chris Shipway'),
  ('LJ75E','Jurgita Toliautaite'),
  ('PTDFK','Lisa Linares-Moreno'),
  ('PTDFK','Crystal D''Silva'),
  ('AFUS6','Róbert Kovács'),
  ('AFUS6','Mónika Zátrok'),
  ('GV324','dr. Németh Emese'),
  ('GV324','Hirsch Anett'),
  ('C2NRU','Giovanni Annese'),
  ('ZGMAH','Anna Alepina'),
  ('ERHPR','Annely Paaps'),
  ('ZGMAL','Alina Miroshnichenko'),
  ('UYCVR','Bettina Buschka'),
  ('3SJY5','Nicolas PALATSIDIS'),
  ('3SJY5','Christelle RUIZ'),
  ('AFUKP','Sanne Weerts'),
  ('24PLH','ORLINSKI Anael'),
  ('24PLH','CHARY Christophe'),
  ('UYCVC','Kiarash Sanei Kashany'),
  ('UYCVC','Sofia'),
  ('6HFCV','Jacobus van Dooren'),
  ('6HFCV','Sabine Hommel'),
  ('YX25R','Marius Lingurariu'),
  ('YX25R','Florentina Irina Ionita'),
  ('UYCT2','amandine Sohier Faure'),
  ('UYCT2','Thierry Sohier Faure'),
  ('GV37E','Laurenz Joos'),
  ('GV37E','Cécile Rüger'),
  ('NP5V5','Clare Paine'),
  ('AFU44','Caroline McGhie'),
  ('3SJLN','Roberto Monegat'),
  ('3SJLN','Immacolata Sepe'),
  ('24PNK','Laeticia BONFILS'),
  ('24PNK','Aurore CHANUT'),
  ('3SJLJ','Dylan John Deighton'),
  ('3SJLJ','Patrycja Lenartowicz'),
  ('4NTPJ','Luis Vidal Gutierrez Vilca'),
  ('4NTPJ','Blanca Salcines Moreno'),
  ('LJ7VT','Tatiana Vogel'),
  ('ZGMTK','Wiktoria Kolzlowska (Jack'),
  ('ZGMTK','Jill Winner at BIG3)'),
  ('C2N9Y','Angela Johnson-Scott'),
  ('C2N9Y','Kevin Scott'),
  ('AFU3M','Catherine Smith'),
  ('AFU3A','Laura Martínez Gálvez'),
  ('ERHZJ','Gerhard Plischek'),
  ('ERHZJ','Aida Emese Schindler'),
  ('KZVYT','Maria Lackner'),
  ('KZVYT','Danica Radulovic'),
  ('AFU33','María RÍos Carrasco'),
  ('AFU33','John Crespo'),
  ('5DZEM','Angela Bönzli'),
  ('HA95P','Hannah Peters'),
  ('YX2VS','Rachael Ryan'),
  ('YX2VS','Charlotte Talia Osman'),
  ('GV3A3','Aurora Martínez Sánchez de Molina'),
  ('GV3A3','Abel Belenguer Garulo'),
  ('5DZEZ','Andrea Gil Martínez'),
  ('T5K79','Stephany Clark'),
  ('C2N3K','Giacomo Caroli'),
  ('AFUFT','Wanisanga'),
  ('AFUFT','Gaelle Gutierrez'),
  ('YX2HT','Christelle Silva Amado'),
  ('YX2HT','Patrícia Alexandra Fernandes Andrade'),
  ('5DZ2D','Ekaterina Dorovskaya'),
  ('DKG9J','Daniëlle ter Linden'),
  ('9UXSJ','David De Clerck'),
  ('C2NCJ','Radu Cristian Moca'),
  ('C2NCJ','Nela Iulia Ionescu'),
  ('F9Y7C','Pop Sergiu-Alexandru'),
  ('F9Y7C','Sandru Iulia Maria'),
  ('YX2LN','Oliwia Stanislawek'),
  ('YX2LN','Honoka Miyaji'),
  ('HA9GE','Carla Carranza'),
  ('4NTER','Silviu Anton'),
  ('4NTER','Mara Lepadatu'),
  ('9UX7D','Liana Jones'),
  ('YX2K2','Laura Rodrigo Perez'),
  ('YX2K2','Idoya Echazarra Escribano'),
  ('PTDSN','Lucia Waldhauer'),
  ('W7RLE','Miss Agnes Pukler'),
  ('3SJTV','Debora Wyss'),
  ('XC93J','Katrin Koller'),
  ('YXFM9','Javier Marquez y Nadia Hoyas'),
  ('YXFM9','TBD - Triple Room'),
  ('YXFAS','KANG SORAN'),
  ('SLVP9','Lucie Koháková'),
  ('LJMTV','Balanica Alina Mihaela'),
  ('LJMTV','Sabou Daria'),
  ('9UHZU','Romane Schneider'),
  ('9UHZU','Georges Onana Awono'),
  ('T5474','Sylvie Bogaert'),
  ('NPCGZ','Olaf Konings'),
  ('NPCGZ','Raats Elisabeth'),
  ('F964A','Samuel Littler'),
  ('4NXZ2','GHISLAIN HULEUX'),
  ('4NXZ2','Mélissa Barragan'),
  ('9UHKA','Anthony Rastelli'),
  ('9UHKA','Mandy Rastelli'),
  ('C2U5N','Gail Coster'),
  ('C2U5N','Beverley Brooks'),
  ('C2UVK','Maria Teresa Munoz Castillo'),
  ('C2UVK','Florian Keller'),
  ('7ELVU','Nadine Sibylla Moll'),
  ('YXFDS','Lidiia Khilkova'),
  ('7EL69','Marian Gherghe'),
  ('7EL69','Delia Bălan'),
  ('W7SS4','JANA KUKK'),
  ('C2RSW','Ricardo Rodriguez'),
  ('T59CP','Shulagh Jacobs'),
  ('F9LF7','Mehran Shahriarifar'),
  ('AFSA7','Avram Ioana'),
  ('AFSA7','Avram Laurentiu'),
  ('AFSA7','Stan Adriana Mihaela'),
  ('AFSA7','Moise Claudia Cristina'),
  ('F9L7J','Paula Rutherford'),
  ('GV2L3','Vizireanu Roxana Andreea'),
  ('GV2L3','Golban Daniel'),
  ('NPAKC','Patrascu Adina'),
  ('NPAKC','Simiganoschi Codruta'),
  ('M3NJ4','Kristof De zutter'),
  ('M3NJ4','Krisztina Kosztancsek'),
  ('SLXG9','Cristina Espinosa Lozano'),
  ('SLXG9','Miriam Lucas Arranz'),
  ('NPWGN','Wolfgang Mayr'),
  ('DK6WK','Nader Gohar'),
  ('DK6WK','Manon Rousselle'),
  ('R6T23','Sirli-Mai Henker'),
  ('R6T23','Iris-Maria Henker'),
  ('24LXJ','He-Young'),
  ('6H5DJ','Ana Rodríguez Velasco'),
  ('ZGAFN','Tihomir Ivanov'),
  ('ZGAFN','Mila Maneva'),
  ('24LJF','Danitza Alegre'),
  ('SLXC4','Paula Gete rodriguez'),
  ('SLXC4','Olivia Ragni'),
  ('NPW7R','Mojtaba Bagheri'),
  ('3SYX2','Raul Gómez Martinez'),
  ('3SYX2','Maria Carrasco Valencia'),
  ('UYVMK','Lloydvos@gmail.com'),
  ('UYVMK','Placeholder'),
  ('LJC2U','Cristina Madrid'),
  ('LJC2U','Daniela Sotelo'),
  ('PT7EL','Noah Cook'),
  ('PT7EL','Sabrina Ziegler'),
  ('ZGAFS','Maria Antonova'),
  ('ZGAFS','Gergana Manolova'),
  ('YXM3N','Frederika Kyi'),
  ('YXM3N','Pascal Reich'),
  ('JW246','Natalie Emmert'),
  ('C2SLH','Nedyalka D Stefanova'),
  ('W74NY','Hansen Tay'),
  ('5DR6J','Irina Rangelova'),
  ('5DR6J','Vyara Kamberska'),
  ('GVF94','Salvador Rubio Coderch'),
  ('C2SLL','Marion Naudts'),
  ('C2SLL','Bie Dillen'),
  ('9UGVV','Amador Gramage Prats'),
  ('9UGVV','Dionisio Malonda Garcia'),
  ('DK6JG','Beatriz Rubio'),
  ('DK6JG','Noemí Garcia'),
  ('DK6JG','María José Platero López “Especial Hab. Triple”'),
  ('NPWM5','Nathalie Moens'),
  ('AFKN3','LUIS MIGUEL GARCIA OLMOS'),
  ('AFKN3','NIEVES PRIETO'),
  ('GVFEX','Marian Margarit'),
  ('GVFEX','Cristina Margarit'),
  ('4NJVK','Eddy AERTS'),
  ('4NJVK','Vera KELLENS'),
  ('R6TCU','Celestino Melgosa'),
  ('R6TCU','Nuria García Rey'),
  ('ZGA7U','Vanessa Anthuenis'),
  ('ZGA7U','Kristof Lievens'),
  ('ERPXD','Barbora Bonham'),
  ('NPWMS','Celia Soria Rojo y Angela García'),
  ('NPWMS','Margarita Carrasco Andrade'),
  ('VM9RJ','Nathalie Pauwels'),
  ('VM9RJ','Esther Verschueren'),
  ('JW29K','Martin Bridge'),
  ('XC3KS','Zubyda Azzam'),
  ('W74UN','Kim Belcher'),
  ('PT733','M J RODRIGUEZ SANCHEZ'),
  ('PT733','MARIA ROSARIO SENDIN GARCIA'),
  ('PT733','SANDRA OLEA HERRERO'),
  ('PT733','NURIA OLEA HERRERO'),
  ('SLXWV','Enrique Ávila'),
  ('SLXWH','Amelie Alberro'),
  ('SLXWH','Sonia Tajouri'),
  ('LJC7W','Ines De Meerleer'),
  ('LJC7W','Nicole Serneels'),
  ('W74R3','Clare Gayler'),
  ('W74R3','Jinling Lewis'),
  ('F9ZYD','Nikki Wright'),
  ('VM9S6','Adriana Ferdean'),
  ('VM9S6','Sarah Crossman'),
  ('ZGAM3','Andrew Singleton'),
  ('GVFDT','Chami Jeon'),
  ('LJCML','taeyoon kim'),
  ('F9ZZC','Alicia Ortega Saiz'),
  ('F9ZZC','Rebeca Villalva Graña'),
  ('YXMM7','Katelijne Goedertier'),
  ('YXMM7','William Haelewijn'),
  ('7EUR5','Danny Verbeke'),
  ('7EUR5','Wendy De Decker'),
  ('DKLND','Ehimare Ogona'),
  ('SLHPT','Renata Kudelkova'),
  ('M3R9M','Goiuri Astigarraga Domenech'),
  ('M3R9M','María Azucena Egea Perea'),
  ('YX5XE','Peter Savory'),
  ('YX5XE','Laura Savory'),
  ('M3R3P','Beatrijs Thibaut'),
  ('M3R3P','Isabelle Geerinck'),
  ('GV7V9','Allison Kelham'),
  ('R6XLD','Derrick Tam'),
  ('UYT62','Hannelore Van Bavel'),
  ('UYT62','Rebecca Ellerington'),
  ('UYT6J','Susie Tse'),
  ('UYT6J','Cliff Richards'),
  ('LJAPG','Della Risden'),
  ('LJAPG','Michael Risden'),
  ('LJAPG','Alison Welbourne'),
  ('LJAPG','Aaliyah Risden'),
  ('NPVLN','Stephane Feusso'),
  ('AF45H','Yatindra Ranade'),
  ('AF45H','Supreme Kaur Bhamra'),
  ('NPVL2','Iara schrott'),
  ('NPVL2','Lorena Fernández Aguado'),
  ('AF45U','Luc Geerinck'),
  ('F9N27','Olivier Romedenne'),
  ('F9N27','Manuel Fernández Pareja'),
  ('SLHRN','Kamila Wesolowska'),
  ('SLHRN','Giovanni Rocca'),
  ('ERYEF','Christine Acker'),
  ('ERYEF','Sophia Schmoll'),
  ('PTMPK','Susanne Pezzella'),
  ('W79W4','Adib Jamil'),
  ('ZGWZT','Vasileva Kameliya'),
  ('ZGWZT','Zawadzka Magdalena'),
  ('ZGWZY','Ralf Sunnus'),
  ('ZGWZY','Volker Langenkamp'),
  ('4NG44','Ana Maria Santiago Rama'),
  ('4NG44','Laura Gonzalez Sanchez'),
  ('UYTR4','Marjorie Lombardo'),
  ('UYTR4','Damien Desrats'),
  ('6HCLS','Carmen Izquierdo Sánchez'),
  ('6HCLS','Laura Rivero Vélez'),
  ('C2KAZ','Lloyd Campbell'),
  ('4NG9X','Jerome Blin'),
  ('KZJ4H','Luke Jacobsen'),
  ('W79VA','Nikolaos Karamanis'),
  ('ERYDM','Carmel Flynn'),
  ('YX5L4','Elvira Agron'),
  ('AF4VY','Giovanni Farotto'),
  ('AF4VY','Tarik Boudraa'),
  ('VMEXS','Gareth Evans'),
  ('VMEXS','Joanna Hodgkinson'),
  ('7EU56','Karima Alem'),
  ('7EU56','Jenny Bjursell'),
  ('6HCZF','thomas schoegje'),
  ('3S62P','Hana Yang'),
  ('3S62P','TBD'),
  ('T53H3','Adedamola Onih'),
  ('NPVRN','Sebastian blank'),
  ('NPVSD','Valesca Kipping'),
  ('YX5Z9','Ulrike Silberkuhl')
)
SELECT
  cc.order_code,
  cc.full_name AS csv_name,
  (SELECT string_agg(g2.full_name, ' | ' ORDER BY g2.full_name)
     FROM guests g2 WHERE g2.order_code = cc.order_code) AS db_names_for_order,
  CASE WHEN (SELECT count(*) FROM guests g3 WHERE g3.order_code = cc.order_code) = 0
       THEN 'order_missing_entirely'
       ELSE 'name_mismatch_only' END AS verdict
FROM csv_canonical cc
LEFT JOIN guests g
  ON g.order_code = cc.order_code
  AND lower(g.full_name) = lower(cc.full_name)
WHERE g.id IS NULL
ORDER BY verdict, cc.order_code, cc.full_name;
